name       : libpillowfight
version    : 0.2.1
release    : 3
source     :
    - https://github.com/jflesch/libpillowfight/archive/0.2.1.tar.gz : 9a00e3636c8ebb00c40c6b0e6f4e6eb5a7ea7618704fdee18e145687f08de13c
license    : MIT
component  : programming.library
summary    : Small library containing various image processing algorithms
description: |
    Really simple C Library containing various image processing algorithms. It includes Python 3
    bindings designed to operate on Pillow images (PIL.Image).
builddeps  :
    - pkgconfig(python3)
    - python-nose
rundeps    :
    - python-pillow
setup      : |
    %cmake .
build      : |
    %make
    %make_install
install    : |
    %python3_setup
    %python3_install
