name       : libpillowfight
version    : 0.2.4
release    : 4
source     :
    - https://github.com/jflesch/libpillowfight/archive/0.2.4.tar.gz : 32933926d9e16c9575c262188eec98c264c4a9505b6674754fff85d1e59cd8dd
license    : GPL-2.0-only
component  : programming.library
summary    : Small library containing various image processing algorithms
description: |
    Really simple C Library containing various image processing algorithms. It includes Python 3 bindings designed to operate on Pillow images (PIL.Image).
builddeps  :
    - pkgconfig(python3)
    - python-nose
rundeps    :
    - python-pillow
setup      : |
    echo "#define INTERNAL_PILLOWFIGHT_VERSION \"$version\"" > src/pillowfight/_version.h
    %cmake . -DLIBDIR=lib%LIBSUFFIX%
build      : |
    %make
    %make_install
install    : |
    %python3_setup
    %python3_install
